### ISSUE TITLE
Different public key for the same key_material (opencl vs rust code)?

### ISSUE THREAD

**Issue by sdrpa** [webmaster128/lisk-vanity#8]
I want to port the project to Swift, played with rust code, it works great, but for OpenCL part, I found that opencl code in ```entry.cl``` generates different public key for the same key_material, comparing it to function:
```pub fn secret_to_pubkey(key_material: [u8; 32], generate_key_type: GenerateKeyType) -> [u8; 32]``` in derivation.rs.
The implementation in derivation.rs works correctly, so I tested entry.cl:

```bip39_entropy_to_mnemonic(key_material+16, menomic_hash);``` gives the same hash as ```entropy_to_mnemonic(cut_last_16(&key_material));``` but after that, the code below (where key = menomic_hash):
```
bignum256modm a;
ge25519 ALIGN(16) A;
u32 in[32] = { 0 };
uchar hash[64];

sha512_ctx_t hasher;
sha512_init (&hasher);
to_32bytes_sha2_input(in, key);
sha512_update (&hasher, in, 32);

sha512_final (&hasher);
from_sha512_result(hash, hasher.h);

hash[0] &= 248;
hash[31] &= 127;
hash[31] |= 64;

expand256_modm(a, hash, 32);
ge25519_scalarmult_base_niels(&A, a);

uchar pubkey[32];
ge25519_pack(pubkey, &A);
```
generates different public key then function
```pub fn secret_to_pubkey(key_material: [u8; 32], generate_key_type: GenerateKeyType) -> [u8; 32]``` in derivation.rs?

**Comment by webmaster128** [comment]
Hi @sdrpa,

okay, first things first. The term `key_material` or `secret_key_material` in the code is used to store either a 32 bytes Ed25519 private key or a 16 bytes BIP39 mnemonic entropy (which can be encoded as 12 words). The key derivation works like

```
mnemonic -> Ed25519 private key -> Ed25519 public key -> Address
   (1)              (2)                 (3)                (4)
```

and you can only derive from the lower number to the higher one and nove vise-versa (i.e. left to right only).

For debugging it is considerably easier to start from point (2), as the (1)->(2) derivation can be ignored until the rest is proven to work. So let's continue with `generate_key_type == GenerateKeyType::PrivateKey` and `key_material` or `secret_key_material` being 32 byte Ed25519 pubkeys.

In #9 I added a test case that takes the input seed `456c62af90d3dfd765b7d4b56038cbe19afa5aea9cf3aa3b1e9e476c8cafbb00` iterates over the last byte in 256 GPU thheads and find the solution `456c62af90d3dfd765b7d4b56038cbe19afa5aea9cf3aa3b1e9e476c8cafbbc2`. This test can be executed with `cargo test` and works fine on my mac as well as on Travis. But feel free to test the same on yout GPU. The new test code for GPU calls should allow you to better debug what exactly goes wrong.

**Comment by webmaster128** [comment]
#10 fixed a serious bug (https://github.com/webmaster128/lisk-vanity/pull/10/commits/ba7264d35da30b5b7c9ee2460e28fe84dd566094), which sometimes resulted in a wrong (3)->(4) derivation.

**Comment by sdrpa** [comment]
Thank you for the prompt reply, I'll test it later today on macbook and macmini and advise.
